<?xml version="1.0"?>
<robot name="differential_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Parámetros básicos -->
  <xacro:property name="wheel_radius" value="0.065"/>
  <xacro:property name="wheel_separation" value="0.5"/>

  <!-- Link principal -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
        <visual>
        <!-- ajusta origen si tu STL no está centrado -->
        <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
        <geometry>
        <mesh
            filename="package://robot_description/meshes/base_link.stl"
            scale="0.003 0.003 0.003"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
        <geometry>
        <mesh
            filename="package://robot_description/meshes/base_link.stl"
            scale="0.003 0.003 0.003"/>
        </geometry>
    </collision>
  </link>

  <!-- Rueda izquierda -->
  <link name="wheel_left_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- Rueda derecha -->
  <link name="wheel_right_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- Rueda loca (caster) -->
  <link name="caster_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.0125"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.0125"/>
      </geometry>
    </collision>
  </link>

  <!-- Uniones de las ruedas al chasis -->
  <joint name="joint_wheel_left" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0 ${-wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="joint_wheel_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="joint_caster" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="-0.2 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Transmissions -->
  <transmission name="trans_wheel_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_wheel_left"/>
    <actuator name="motor_left"/>
  </transmission>
  <transmission name="trans_wheel_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_wheel_right"/>
    <actuator name="motor_right"/>
  </transmission>

</robot>