<?xml version="1.0"?>
<robot name="differential_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Par치metros b치sicos -->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_separation" value="0.095"/>

  <!-- Link principal (chasis en gris) -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.12 0.05"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.12 0.05"/>
      </geometry>
    </collision>
  </link>

  
  <!-- Ruedas motrices (en negro) -->
  <link name="wheel_left_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <link name="wheel_right_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

  <!-- Caster de bola (en negro) -->
  <!-- 1) Montaje fijo -->
  <link name="caster_mount_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.01"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.01"/>
      </geometry>
    </collision>
  </link>
  <joint name="caster_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_mount_link"/>
    <origin xyz="-0.035 0 -0.035" rpy="0 0 0"/>
  </joint>

  <!-- 2) Eje de rotaci칩n roll (X) -->
  <link name="caster_roll_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.005"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.005"/>
      </geometry>
    </collision>
  </link>
  <joint name="caster_roll_joint" type="continuous">
    <parent link="caster_mount_link"/>
    <child link="caster_roll_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <!-- 3) Eje de rotaci칩n pitch (Y) con la bola -->
  <link name="caster_ball_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.0125"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.0125"/>
      </geometry>
    </collision>
  </link>
  <joint name="caster_pitch_joint" type="continuous">
    <parent link="caster_roll_link"/>
    <child link="caster_ball_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Joints de ruedas motrices -->
  <joint name="joint_wheel_left" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.025 ${-wheel_separation/2} -0.01" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  <joint name="joint_wheel_right" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.025 ${wheel_separation/2} -0.01" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Transmissions. Creo que s epueden quitar -->
  <transmission name="trans_wheel_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_wheel_left"/>
    <actuator name="motor_left"/>
  </transmission>
  <transmission name="trans_wheel_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_wheel_right"/>
    <actuator name="motor_right"/>
  </transmission>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>
  <gazebo reference="wheel_left_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="wheel_right_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="caster_mount_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="caster_roll_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="caster_ball_link">
    <material>Gazebo/Blue</material>
  </gazebo>


</robot>