controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    # Publicar estados de articulaciones (necesario para TF, RViz, etc.)
    joint_state_broadcaster:
      ros__parameters:
        type: joint_state_broadcaster/JointStateBroadcaster

    # Control diferencial (recibe cmd_vel → mueve ruedas)
    diff_drive_controller:
      ros__parameters:
        type: diff_drive_controller/DiffDriveController
        publish_rate: 50.0
        base_frame_id: base_link
        left_wheel_names: ['joint_wheel_left']
        right_wheel_names: ['joint_wheel_right']
        wheel_separation: 0.095
        wheel_radius: 0.0325
        use_stamped_vel: false
        linear.x.has_velocity_limits: true
        linear.x.max_velocity: 0.5
        angular.z.has_velocity_limits: true
        angular.z.max_velocity: 1.0
        odom_frame_id: odom
        base_frame_id: base_link
        publish_odom: true
        publish_odom_tf: true
        publish_wheel_tf: true
        open_loop: true
        enable_odom_tf: true

      # ----------------------------------------------
      # Parámetros mínimos obligatorios para que funcione
      # publish_rate: 50.0                   # Frecuencia de publicación de odometría en Hz
      # base_frame_id: base_link             # Nombre del frame base de tu robot
      # left_wheel_names: ['joint_wheel_left']
      # right_wheel_names: ['joint_wheel_right']
      # wheel_separation: 0.095              # Distancia entre ruedas (metros)
      # wheel_radius: 0.0325                 # Radio de cada rueda (metros)
      # use_stamped_vel: false               # Esperar mensajes en /cmd_vel (Twist) sin sello de tiempo
      # linear.x.has_velocity_limits: true   # Habilita límites de velocidad lineal
      # linear.x.max_velocity: 0.5           # Velocidad lineal máxima (m/s)
      # angular.z.has_velocity_limits: true  # Habilita límites de velocidad angular
      # angular.z.max_velocity: 1.0          # Velocidad angular máxima (rad/s)
      # ----------------------------------------------

      # Opcionales:
      # cmd_vel_timeout: 0.5                 # Tiempo (s) tras el cual, sin recibir cmd_vel, se detiene
      # odom_topic: "odom"                   # Nombre del topic donde publica odometría
      # odom_frame_id: "odom"                # Frame de odometría
      # base_frame_id: "base_link"           # Frame base del robot

      # Y otros parámetros avanzados de control…
