controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['joint_wheel_left']
    right_wheel_names: ['joint_wheel_right']
    wheel_separation: 0.4
    wheel_radius: 0.05
    use_stamped_vel: false
    
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0
    
    odom_frame_id: odom
    publish_odom: true
    publish_odom_tf: true
    publish_wheel_tf: true
    open_loop: true
    enable_odom_tf: true