controller manager:
  ros_parameters:
    update_rate: 30
    use_sim_true: true 

    diff cont:
      type: diff_drive_controller/diff_drive_controller
    
    joint broad:
      type: joint_state_broadcaster/JointStateBoadcaster

diff cont:
  ros_parameters:
    publish_rate: 50.0
    base_frame_id: base_link

    left_wheel_names: ['joint_wheel_left']
    right_wheel_names: ['joint_wheel_right']
    wheel_separation: 0.095
    wheel_radius: 0.0325

    use_stamped_vel: false